#!/bin/bash
export http_proxy=""
export https_proxy=""
rm wallpaper*
wget -q imgur.com/r/wallpapers
grep -oE id=[^\\]{10}class=\"post\"\> wallpapers>walls
IFS=$'\n'      
for j in `cat ./walls`
do
j=$(echo $j|cut -c5-|rev|cut -c16-|rev)
wget -nc http://imgur.com/$j.jpg -P /tmp
#id=$(wget -q http://bing.com -O -| grep -o url:[^' '\\]*jpg|cut -c6-)
#wget -nc http://bing.com"$id"
#mv *jpg back.jpg
#gsettings set org.gnome.desktop.background picture-uri "file:///home/rishabh/Bing/back.jpg"
gsettings set org.gnome.desktop.background picture-uri "file:///tmp/$j.jpg"
sleep 300
done
./imgur
