#!/bin/bash
export http_proxy=""
export https_proxy=""
while true; do
    # testing...
    LC_ALL=C nmcli -t -f DEVICE,STATE dev | grep -q "^wlan0:connected$"
    if [ $? -eq 0 ]; then
        break
    else
        # not connected, sleeping for a second
        sleep 1
    fi
done
wget -q http://momentumdash.com/app/backgrounds.json
cat backgrounds.json | grep -o https://www.flickr.com/photos[^\"]*>flickr
cat backgrounds.json | grep -o http://500px.com/photo[^\"]*>px
#rm backgrounds.json
cat flickr px > walls.log
rm flickr px
IFS=$'\n'
for j in `cat ./walls.log`
do
temp=$(echo $j|cut -c 13-18)
if [ "$temp" == "flickr" ]
then 
	j=$(echo $j/sizes/l)
	echo "Downloading from Flickr";
	id=$(wget -q $j -O -|grep -o https://farm[^\"]*b.jpg)
	echo "Downloading url $id";
else 
	echo "Downloading from 500px";
	id=$(wget -q $j -O -|grep -o https://ppcdn.500px.org/[^\"]*2048.jpg)
	echo "Downloading url $id";
fi
wget -nc $id
j=$(ls|grep *.jpg)
mv *.jpg /tmp
gsettings set org.gnome.desktop.background picture-uri "file:///tmp/$j"
sleep 300
rm /tmp/*.jpg
done

